<?php

use Drupal\Core\Routing\RouteMatchInterface;
function api_redoc_document_preprocess_page(&$variables) {
    $variables['#attached']['library'][] =  'api_redoc_document/api_redoc_document';
  }

/**
 * Implements hook_help().
 */
function api_redoc_document_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.api_redoc_document') {
    return t('<h1>OpenApi Redoc UI Converter</h1></br>

    <strong>This module provides a Redoc Converter which will convert your OpenApi file into a valid document format. It provides a functionality where you can show your OpenApi document formatted style on the Page, along with your node data.</strong></br>
    
    1. Install module using Drush or using Drupal UI</br>
    
    2. For this, you need to add redoc  tag in you page while adding/editing a node.</br>
    
    3. The format of the field should be full HTML to support the redoc tag, it will not work with any other format if not supported.</br>
    
    4. The format of the tag should be like below:-</br>
    <h2>
    <strong><redoc spec-url="testapipath/testname.json">
    </redoc></strong></h2></br>
    
    URL is the open API valid URL or the valid file path. The format of the file should be json or yml. If any other format is used than the module will not work as expected.');
  }
}
